services:
  app:
    build: .
    container_name: app
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: postgres:16.2
    container_name: db
    restart: unless-stopped
    shm_size: 128mb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2
    container_name: redis
    restart: unless-stopped
    volumes:
      - rdata:/data
    ports:
      - ${REDIS_PORT}:6379
    healthcheck:
      test: redis-cli ping | grep PONG || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
  rdata:
