services:
  db:
    image: postgres:16.2
    restart: always
    shm_size: 128mb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}

  redis:
    image: redis:7.2
    restart: always
    volumes:
      - rdata:/data
    ports:
      - ${REDIS_PORT}:6379

    depends_on:
      - db

volumes:
  pgdata:
  rdata:
